# @package _global_

defaults:
  - /benchmark/rearrange: multi_agent_tidy_house_fp
  - /habitat_baselines: habitat_baselines_rl_config_base
  - /habitat/simulator/sim_sensors@habitat_baselines.eval.extra_sim_sensors.third_rgb_sensor: third_rgb_sensor
  - /habitat_baselines/rl/agent: pop_play
  - /habitat_baselines/rl/policy/obs_transforms@habitat_baselines.rl.policy.agent_0.obs_transforms.add_virtual_keys:
    - add_virtual_keys_base
  - /habitat_baselines/rl/policy/obs_transforms@habitat_baselines.rl.policy.agent_1.obs_transforms.add_virtual_keys:
    - add_virtual_keys_base
  - /habitat_baselines/rl/policy@habitat_baselines.rl.policy.agent_0: hl_fixed #hab3_hl_neural_ma
  - /habitat_baselines/rl/policy@habitat_baselines.rl.policy.agent_1: hl_fixed #hab3_hl_neural_ma
  - /habitat_baselines/rl/policy/hierarchical_policy/defined_skills@habitat_baselines.rl.policy.agent_0.hierarchical_policy.defined_skills: oracle_skills_ma
  - /habitat_baselines/rl/policy/hierarchical_policy/defined_skills@habitat_baselines.rl.policy.agent_1.hierarchical_policy.defined_skills: oracle_skills_ma_humanoid
  - /habitat/task/measurements:
    - composite_subgoal_reward
    - runtime_perf_stats
    #- panoptic_calculator
  - /habitat/task/lab_sensors:
    - relative_resting_pos_sensor
    - target_start_sensor
    - goal_sensor
    - is_holding_sensor
    - end_effector_sensor
    - target_start_gps_compass_sensor
    - target_goal_gps_compass_sensor
    - localization_sensor
    - has_finished_oracle_nav
    - other_agent_gps
  - /habitat/task/actions@habitat.task.actions.agent_0_arm_action: arm_action
  - override /habitat/task/rearrange: multi_agent_tidy_house_base_spot
  # For Spot observation space
  - override /habitat/simulator/agents@habitat.simulator.agents.agent_0: rgbd_head_rgbdp_arm_agent
  - override /habitat/simulator/agents@habitat.simulator.agents.agent_1: rgbdp_head_agent
  - _self_

hydra:
  job:
    name: 'pop_play_humanoid_spot_fp'

habitat:
  dataset:
    data_path: data/datasets/apr_23/jsons/s_easy_test_unseen_50.json.gz
  task:
    save_action_sequences:
      True #False
    # read_action_sequences:
    #   True
    save_dir:
      "../save_dirs/aug_16_panoptic_fbe"
    actions:
      # agent_0_base_velocity:
      #   agent_index: 0
      #   lin_speed: 40.0
      #   ang_speed: 40.0
      agent_0_oracle_nav_with_backing_up_action:
        type: OracleNavWithBackingUpAction
        # type: OracleNavWithBackingUpAction
        spawn_max_dist_to_obj: -1.0
        # For noncylinder navmesh action
        # If we allow the agent to do sliding
        allow_dyn_slide: True #False
        allow_back: False
        # If the agent is allowed to slide if the agent needs to do rotation
        enable_rotation_check_for_dyn_slide: True #False
        # The distance threshold of treating collision
        collision_threshold: 0.02 #0.0 #0.02 #0.02
        # The navmesh offset for the action control
        navmesh_offset: [[0.0, 0.0], [0.0, 0.0], [-0.0, 0.0]]
        # The navmesh offset for the agent placement
        navmesh_offset_for_agent_placement: [[0.0, 0.0], [0.15, 0.0], [-0.15, 0.0]]
        enable_lateral_move: True
        #turn_thresh: 0.1
        dist_thresh: 1 #0.5 #1.25
        # lateral_lin_speed: 40.0
        # longitudinal_lin_speed: 40.0
        # lin_speed: 40.0
        # ang_speed: 40.0
        turn_thresh: 0.15 #0.26166666666
        # dist_thresh: 0.5
        # ang_speed: 62.8330734681 #94.2496102022 #40.0 #94.2496102022 #40 #94.2496102022 #60.0 #94.2496102022 #90.0
      agent_0_arm_action:
        grip_controller: MagicGraspAction
      agent_1_oracle_nav_with_backing_up_action:
        motion_control: human_joints
        spawn_max_dist_to_obj: -1
    robot_at_thresh: 3.0
  environment:
    max_episode_steps: 5000 #2000 #2000 #5000

  gym:
    obs_keys:
      - agent_0_articulated_agent_arm_depth
      - agent_0_articulated_agent_arm_rgb
      - agent_0_articulated_agent_arm_panoptic
      - agent_0_articulated_agent_arm_depth_down
      - agent_0_articulated_agent_arm_rgb_down
      - agent_0_articulated_agent_arm_panoptic_look_down
      - agent_0_relative_resting_position
      #- agent_0_obj_start_sensor
      #- agent_0_obj_goal_sensor
      #- agent_0_obj_start_gps_compass
      #- agent_0_obj_goal_gps_compass
      - agent_0_is_holding
      - agent_0_ee_pos
      - agent_0_localization_sensor
      - agent_0_has_finished_oracle_nav
      #- agent_0_other_agent_gps
      - agent_1_head_depth
      - agent_1_head_panoptic
      - agent_1_relative_resting_position
      #- agent_1_obj_start_sensor
      #- agent_1_obj_goal_sensor
      #- agent_1_obj_start_gps_compass
      #- agent_1_obj_goal_gps_compass
      - agent_1_is_holding
      - agent_1_ee_pos
      - agent_1_localization_sensor
      - agent_1_has_finished_oracle_nav
      #- agent_1_other_agent_gps
  simulator:
    # Add Spot robot agents
    agents:
      agent_0:
        radius: 0.001 #0000001 #0.3 #0.05 #0.25
        height: 0.8 #0.000000001 #0.8
        articulated_agent_urdf: data/robots/hab_spot_arm/urdf/hab_spot_arm.urdf
        articulated_agent_type: "SpotRobot"
        sim_sensors:
          arm_rgb_sensor:
            height: 480 #224 #480
            width: 640 #171 #640
            hfov: 79 #47 #79 #79 #47
          arm_depth_sensor:
            height: 480 #224 #480 #224
            width: 640 #171 #640 #171
            hfov: 79 #47 #79
          arm_panoptic_sensor:
            height: 480
            width: 640
            hfov: 79 #47 #79
          arm_rgb_down_sensor:
            height: 480 #224 #480
            width: 640 #171 #640
            hfov: 79 #47 #79 #79 #47
          arm_depth_down_sensor:
            height: 480 #224 #480 #224
            width: 640 #171 #640 #171
            hfov: 79 #47 #79
          arm_panoptic_look_down_sensor:
            height: 480
            width: 640
            hfov: 79 #47 #79
          head_rgb_sensor:
            height: 480
            width: 640
            hfov: 79 #47 #79
          # head_stereo_left:
          #   height: 480
          #   width: 640
          #   hfov: 79 #47 #79
          # head_stereo_right:
          #   height: 480
          #   width: 640
          #   hfov: 79 #47 #79
      agent_1:
        #radius: 0.25 #0000001 #0.3 #0.05 #0.25
        #height: 0.8 #0.000000001 #0.8
        articulated_agent_urdf: 'data/humanoids/humanoid_data/female2_0.urdf'
        articulated_agent_type: 'KinematicHumanoid'
        rest_pose_data_path: 'data/humanoids/humanoid_data/standing_pose_smplx.pkl'
        motion_data_path: "data/humanoids/humanoid_data/walking_motion_processed_smplx.pkl"
    kinematic_mode: True
    ac_freq_ratio: 1
    step_physics: False
    habitat_sim_v0:
      allow_sliding: True

habitat_baselines:
  verbose: False
  trainer_name: "ddppo"
  updater_name: "HRLPPO"
  distrib_updater_name: "HRLDDPPO"
  torch_gpu_id: 0
  video_fps: 30
  video_dir: ${hydra:sweep.dir}/${hydra:sweep.subdir}/video
  tensorboard_dir: ${hydra:sweep.dir}/${hydra:sweep.subdir}/tb
  eval_ckpt_path_dir: ${hydra:sweep.dir}/${hydra:sweep.subdir}/checkpoints
  checkpoint_folder: ${hydra:sweep.dir}/${hydra:sweep.subdir}/checkpoints
  log_file: ${hydra:sweep.dir}/${hydra:sweep.subdir}/train.log
  num_environments: 32
  num_updates: -1
  total_num_steps: 1e8
  log_interval: 1
  num_checkpoints: 10
  force_torch_single_threaded: True
  eval_keys_to_include_in_name: ['composite_success']
  load_resume_state_config: False
  rollout_storage_name: "HrlRolloutStorage"

  evaluate: False
  # writer_type: 'wb'

  # wb:
  #   project_name: 'hab3'
  #   entity: 'andrew-colab'
  #   run_name: ${hydra:job.name}_${now:%Y-%m-%d}_${now:%H-%M-%S}

  eval:
    should_load_ckpt: False
    video_option: ["disk"]

  rl:
    agent:
      num_pool_agents_per_type: [1, 8]
      agent_sample_interval: 20
      force_partner_sample_idx: -1
    policy:
      agent_0:
        hierarchical_policy:
          high_level_policy:
            add_arm_rest: False
            policy_input_keys:
              - "articulated_agent_arm_depth"
              - "is_holding"
              - "obj_start_gps_compass"
              - "obj_goal_gps_compass"
              - "other_agent_gps"
          # Override to use the oracle navigation skill (which will actually execute navigation).
          defined_skills:
            nav_to_obj:
              skill_name: "OracleNavPolicy"
              obs_skill_inputs: ["obj_start_sensor", "abs_obj_start_sensor", "obj_goal_sensor", "abs_obj_goal_sensor"]
              max_skill_steps: 1500
      agent_1:
        hierarchical_policy:
          high_level_policy:
            add_arm_rest: False
            policy_input_keys:
              - "head_depth"
              - "is_holding"
              - "obj_start_gps_compass"
              - "obj_goal_gps_compass"
              - "other_agent_gps"
          # Override to use the oracle navigation skill (which will actually execute navigation).
          defined_skills:
            nav_to_obj:
              skill_name: "OracleNavPolicy"
              obs_skill_inputs: ["obj_start_sensor", "abs_obj_start_sensor", "obj_goal_sensor", "abs_obj_goal_sensor"]
              max_skill_steps: 1500

    ppo:
      # ppo params
      clip_param: 0.2
      ppo_epoch: 1
      num_mini_batch: 2
      value_loss_coef: 0.5
      entropy_coef: 0.0001
      lr: 2.5e-4
      eps: 1e-5
      max_grad_norm: 0.2
      num_steps: 128
      use_gae: True
      gamma: 0.99
      tau: 0.95

    ddppo:
      sync_frac: 0.6
      # The PyTorch distributed backend to use
      distrib_backend: NCCL
      # Visual encoder backbone
      pretrained_weights: data/ddppo-models/gibson-2plus-resnet50.pth
      # Initialize with pretrained weights
      pretrained: False
      # Initialize just the visual encoder backbone with pretrained weights
      pretrained_encoder: False
      # Whether the visual encoder backbone will be trained.
      train_encoder: True
      # Whether to reset the critic linear layer
      reset_critic: False
      # Model parameters
      backbone: resnet18
      rnn_type: LSTM
      num_recurrent_layers: 2
